---
- name: Ejecutar script SQL en Windows
  hosts: all
  vars:
    nombre_del_servidor: "10.0.10.51"
    usuario: "pe280\jegoavil"
    contraseña: "Acity2023"
    nombre_de_la_base_de_datos: "AWX"
  tasks:
    - name: Ejecutar script SQL
      win_shell: |
        Invoke-Sqlcmd -ServerInstance {{ nombre_del_servidor }} -Username {{ usuario }} -Password {{ contraseña }} -Database {{ nombre_de_la_base_de_datos }} -Query "SELECT * FROM Heroes WHERE tipo_heroe = 'fuerza'"
