---
- name: Ejecutar script SQL en Windows
  hosts: all
  tasks:
    - name: Ejecutar script SQL
      win_shell: |
        Invoke-Sqlcmd -ServerInstance "10.0.10.51" -Username "pe280\jegoavil" -Password "Acity2023" -Database "AWX" -Query "SELECT * FROM Heroes WHERE tipo_heroe = 'fuerza'"
